spring:
  application:
    name: app
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # Включаем виртуальные потоки (Project Loom)
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:clue_db}
    username: ${DB_USER:cluser}
    password: ${DB_PASS:cluser}
    driver-class-name: org.postgresql.Driver

    hikari:
      # Оптимизация для высоконагруженных систем
      pool-name: ClutchHikariPool
      maximum-pool-size: 20 # Для виртуальных потоков не нужно слишком много, лучше качественный тюнинг
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      # Важно для надежности транзакций
      auto-commit: false

  jpa:
    open-in-view: false # Архитекторский must-have: защищает от LazyInitializationException в контроллерах
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate # Только валидация, миграции доверяем Liquibase
    properties:
      hibernate:
        # Магия Multi-tenancy
        multiTenancy: DISCRIMINATOR

        # Указываем Hibernate, кто будет поставлять текущий ID компании
        tenant_identifier_resolver: com.clutch.app.config.TenantIdentifierResolver

        # Оптимизация пакетной вставки (batching) — критично для импорта данных
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true

        # Форматирование SQL для удобства отладки в dev-режиме
        format_sql: true

  # Настройка миграций
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public

  cache:
    type: redis
    time-to-live: 3600s # 1 час, если метаданные не менялись
    cache-null-values: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      lettuce:
        pool:
          max-active: 64
          max-idle: 16
          min-idle: 8

clutch:
  quotas:
    max-forms: 10

springdoc:
  api-docs:
    path: /v3/api-docs
    # OpenAPI 3.1 для корректной валидации JSONB-схем
    version: openapi_3_1
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  # Включаем Scalar UI
  scalar:
    enabled: true
    path: /scalar

#logging:
#  level:
#    org.springframework.jdbc.core.JdbcTemplate: DEBUG